scrape_configs:
  - job_name: 'client'
    scrape_interval: 10s
    dns_sd_configs:
      - names:
          - client
        port: 8888
        type: A
  - job_name: 'envoy'
    scrape_interval: 10s
    metrics_path: /stats/prometheus
    dns_sd_configs:
      - names:
          - envoyadmin
        port: 10001
        type: A
  - job_name: 'tunnel'
    scrape_interval: 10s
    dns_sd_configs:
      - names:
          - tunnel
        port: 8888
        type: A